// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgBDA7k0Fk0vBq5PUHzu1NsHEw8ChI9M',
    appId: '1:85316744814:web:550668b9dc4c3a5a14d87f',
    messagingSenderId: '85316744814',
    projectId: 'dachdecker-app-v999kq',
    authDomain: 'dachdecker-app-v999kq.firebaseapp.com',
    storageBucket: 'dachdecker-app-v999kq.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhKWEjqOAid-DvaKu8J3HKR1l_eMW4YJU',
    appId: '1:85316744814:android:0ea06cc5146c8abf14d87f',
    messagingSenderId: '85316744814',
    projectId: 'dachdecker-app-v999kq',
    storageBucket: 'dachdecker-app-v999kq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQC1z0Daq6jxVL_UEbrv0LWz-ZY4yUvSk',
    appId: '1:85316744814:ios:f8d38f435c8119c014d87f',
    messagingSenderId: '85316744814',
    projectId: 'dachdecker-app-v999kq',
    storageBucket: 'dachdecker-app-v999kq.appspot.com',
    iosBundleId: 'com.example.dachdeckerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQC1z0Daq6jxVL_UEbrv0LWz-ZY4yUvSk',
    appId: '1:85316744814:ios:f8d38f435c8119c014d87f',
    messagingSenderId: '85316744814',
    projectId: 'dachdecker-app-v999kq',
    storageBucket: 'dachdecker-app-v999kq.appspot.com',
    iosBundleId: 'com.example.dachdeckerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpgBDA7k0Fk0vBq5PUHzu1NsHEw8ChI9M',
    appId: '1:85316744814:web:4cfe481cfa51906c14d87f',
    messagingSenderId: '85316744814',
    projectId: 'dachdecker-app-v999kq',
    authDomain: 'dachdecker-app-v999kq.firebaseapp.com',
    storageBucket: 'dachdecker-app-v999kq.appspot.com',
  );

}